version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USR}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PWD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  telegraf:
    image: telegraf:1.29
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    #environment:
     # - HOST_PROC=/host/proc
     # - HOST_SYS=/host/sys
     # - HOST_ETC=/host/etc
    #network_mode: service:influxdb
    pid: "host"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRF_USR}
      - GF_SECURITY_ADMIN_PASSWORD=${GRF_PWD}
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
